export const money=n=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN',minimumFractionDigits:2}).format(Number(n)||0).replace('PEN','S/');
export function localDate(date=new Date(),timeZone='America/Lima'){const parts=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const value=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${value.year}-${value.month}-${value.day}`;}
export const today=()=>localDate();
export function balances(funds,txs){const map=Object.fromEntries(funds.map(f=>[f.id,Number(f.initial)||0]));for(const t of txs){const n=Number(t.amount)||0;if(t.type==='income')map[t.fund]=(map[t.fund]||0)+n;if(t.type==='expense')map[t.fund]=(map[t.fund]||0)-n;if(t.type==='transfer'){map[t.from]=(map[t.from]||0)-n;map[t.to]=(map[t.to]||0)+n;}}return map;}
export function summary(funds,txs,date=today()){const ym=(typeof date==='string'?date:localDate(date)).slice(0,7),bal=balances(funds,txs);const month=txs.filter(t=>t.date?.startsWith(ym));const income=sum(month.filter(t=>t.type==='income')),expense=sum(month.filter(t=>t.type==='expense'));const total=Object.values(bal).reduce((a,b)=>a+b,0);const protectedMoney=funds.filter(f=>f.protected||!f.spendable).reduce((a,f)=>a+(bal[f.id]||0),0);return{bal,total,protectedMoney,available:total-protectedMoney,income,expense,balance:income-expense};}
const sum=a=>a.reduce((n,t)=>n+Number(t.amount||0),0);
export function byCategory(txs,type='expense'){return Object.entries(txs.filter(t=>t.type===type).reduce((a,t)=>(a[t.category]=(a[t.category]||0)+Number(t.amount),a),{})).sort((a,b)=>b[1]-a[1]);}
export function limitState(p,settings){if(p>=100)return['Alcanzaste o superaste tu límite','negative'];if(p>=settings.critical)return['Estás cerca de alcanzar tu límite','negative'];if(p>=settings.warning)return['Ya utilizaste gran parte de tu presupuesto',''];return['Estás dentro de tu presupuesto','positive'];}
export function dateRange(preset,now=today(),custom={}){const end=custom.end||now;if(preset==='custom')return{start:custom.start||end,end};const currentMonth=now.slice(0,7);if(preset==='previous'){const ym=shiftMonth(currentMonth,-1);return{start:`${ym}-01`,end:lastDay(ym)}}const months=Math.max(1,Number(preset)||1),startMonth=months===1?currentMonth:shiftMonth(currentMonth,-months);return{start:`${startMonth}-01`,end};}
export const inRange=(txs,range)=>txs.filter(t=>t.date>=range.start&&t.date<=range.end);
export function monthlySeries(txs,range){const result=[],rangedTransactions=inRange(txs,range);let cursor=range.start.slice(0,7);const end=range.end.slice(0,7);while(cursor<=end){const monthTransactions=rangedTransactions.filter(t=>t.date?.startsWith(cursor));result.push({month:cursor,income:sum(monthTransactions.filter(t=>t.type==='income')),expense:sum(monthTransactions.filter(t=>t.type==='expense'))});cursor=nextMonth(cursor)}return result;}
export function balanceEvolution(funds,txs,range){const before=txs.filter(t=>t.date<range.start),initial=Object.values(balances(funds,before)).reduce((a,b)=>a+b,0);let running=initial;return txs.filter(t=>t.date>=range.start&&t.date<=range.end&&t.type!=='transfer').sort((a,b)=>a.date.localeCompare(b.date)).map(t=>({date:t.date,balance:running+=t.type==='income'?Number(t.amount):-Number(t.amount)}));}
function nextMonth(ym){const [y,m]=ym.split('-').map(Number);return m===12?`${y+1}-01`:`${y}-${String(m+1).padStart(2,'0')}`;}
function shiftMonth(ym,offset){const [year,month]=ym.split('-').map(Number),index=year*12+month-1+offset,nextYear=Math.floor(index/12),nextMonth=index-nextYear*12+1;return `${nextYear}-${String(nextMonth).padStart(2,'0')}`;}
function lastDay(ym){const [y,m]=ym.split('-').map(Number);return `${ym}-${String(new Date(y,m,0).getDate()).padStart(2,'0')}`;}
